### ISSUE TITLE
Is this project still in development?

### ISSUE THREAD

**Issue by ShalokShalom** [knowthelist/knowthelist#15]
Is knowthelist in coma?

**Comment by knowthelist** [comment]
There hasn't been any feedback, participation, engagement, interests or ideas from other users since I released this project. For me the player is ready to use and I did a lot of parties with "knowthelist". Therefore: no need for development right now

**Comment by ShalokShalom** [comment]
Users tend to give very less feedback - that does not include, that they do not use them. 
Package maintainers will refuse to include and keep it in there repos, when there is no update for a long time.
Is see Gstreamer 1.0 is in use since 2014 and the documentation seems to be superb, so i give it a try.

**Comment by knowthelist** [comment]
knowthelist still uses GStreamer 1.0 if it is available, as far as I can remember

**Comment by ShalokShalom** [comment]
yeah, thats what i mean: its a compliment, since some (rare) projects still depend on 0.10
and the very most projects port their app much later to 1.0, like Clementine. :+1:
