### ISSUE TITLE
Reproducible Builds -Unique Build ID

### ISSUE THREAD

**Issue by heavyarms81** [knowthelist/knowthelist#21]
Knowthelist_2.3 .0_2 is not reproducible as indicated in the Debain Reproducible Builds site. The issue is differences in the NT_GNU_BUILD_ID (unique build ID bitstring). To patch this issue, I have removed the Build ID through the Makefile. The debdiff file is attached to this message.
[patched_differences.zip](https://github.com/knowthelist/knowthelist/files/1471850/patched_differences.zip)

**Comment by knowthelist** [comment]
What does that mean? I've got no glue what you want. 20000 lines of diff ??? You must be kidding!
